import { PortfolioData, ProjectDetailProps } from "@/app/portfolio/_types";

export const PORTFOLIO_DATA: PortfolioData = {
  profile: {
    name: "정재민",
    title: "프론트엔드 개발자",
    subtitle: "접근성과 성능을 기본으로, 누구나 쓰기 쉬운 웹을 만듭니다.",
    photoUrl: "/profile.png",
    page: "Portfolio",
  },
  contact: {
    email: "woals7480@gmail.com",
    phone: "010-8440-7480",
    github: {
      href: "https://github.com/woals7480",
      label: "github.com/woals7480",
    },
  },
  career: [
    {
      role: "프론트엔드 개발자",
      org: "(주) 이음",
      period: "2023.07 – 2025.06",
      bullets: [
        "Vue3 기반 관리자페이지 프론트엔드 개발 및 유지보수",
        "- 하자접수, 예약일정 관리, 문서 출력, 엑셀 다운로드 등 기능 구현",
        "React Native 기반 입주민앱 프론트엔드 개발 및 유지보수",
        "- 하자접수, 예약일정 관리, 푸시알림 등 핵심 기능 구현",
      ],
    },
  ],
  skills: [
    {
      key: "lang",
      label: "Language / Markup",
      color: "#ef4444",
      skills: ["HTML", "CSS", "JavaScript", "TypeScript"],
    },
    {
      key: "fe",
      label: "Frontend Framework",
      color: "#3b82f6",
      skills: ["React", "Next.js", "React Native", "Vue3"],
    },
    {
      key: "state",
      label: "State & Data",
      color: "#06b6d4",
      skills: ["React Query", "Redux", "Vuex", "Recoil", "Zustand"],
    },
    {
      key: "style",
      label: "Styling / UI",
      color: "#a855f7",
      skills: ["Emotion", "Vuetify", "vanilla-extract"],
    },
    //   {
    //     key: "backend",
    //     label: "Runtime / Backend",
    //     color: "#f59e0b",
    //     skills: ["Node.js"],
    //   },
    {
      key: "api",
      label: "API",
      color: "#fb7185",
      skills: ["REST API", "GraphQL", "Socket.IO"],
    },
  ],
  projects: [
    {
      id: "chaedle-admin",
      title: "채들 어드민",
      cover: "/chaedle_admin3.jpg",
      period: { start: "2025/01", end: "2025/05" },
      tags: [
        "Vue3",
        "TypeScript",
        "Vuex",
        "Vuetify",
        "Socket.IO",
        "pdfmake",
        "Chart.js",
        "xlsx",
      ],
      badges: ["회사 프로젝트"],
    },
    {
      id: "chaedle",
      title: "채들",
      period: { start: "2023/08", end: "2024/03" },
      cover: "/chaedle.jpg",
      tags: ["React Native", "Typescript", "Redux", "SQLite", "Socket.IO"],
      badges: ["회사 프로젝트"],
    },
    {
      id: "zcom",
      title: "Zcom",
      cover: "/zcom.png",
      tags: [
        "Next.js",
        "TypeScript",
        "React Query",
        "Next Auth",
        "Socket.IO",
        "MSW",
        "Zustand",
      ],
      badges: ["개인 프로젝트"],
      links: {
        github: "https://github.com/woals7480/zcom-next",
      },
    },
    {
      id: "market",
      title: "딸기마켓",
      cover: "/market.png",
      tags: [
        "Next.js",
        "TypeScript",
        "Recoil",
        "GraphQL",
        "Apollo GraphQL",
        "Emotion",
      ],
      badges: ["개인 프로젝트"],
      links: {
        github: "https://github.com/woals7480/freeboard_frontend",
      },
    },
  ],
};

export const PROJECTS_DATA: ProjectDetailProps[] = [
  {
    id: "chaedle-admin",
    title: "채들 관리자페이지",
    period: { start: "2025.01", end: "2025.05" },
    images: [
      { src: "/chaedle_admin3.jpg", alt: "채들 어드민" },
      { src: "/chaedle_admin2.jpg", alt: "채들 어드민2" },
    ],
    callout:
      "입주민 앱에서 들어온 하자·예약 데이터를 실시간으로 확인하고 피드백/처리 현황을 관리하는 통합 관리자페이지입니다.",
    links: [],
    stacks: [
      "Vue3",
      "TypeScript",
      "Vuex",
      "Vuetify",
      "Socket.IO",
      "pdfmake",
      "Chart.js",
      "xlsx",
    ],
    features: [
      "- 대시보드: Chart.js 기반 핵심 지표 시각화",
      "- 하자 관리: 목록(검색/필터/페이징)·등록·검색·상세·상태 변경",
      "- 예약 관리: 목록(검색/필터/페이징)·등록·검색·상세·상태 변경 + Socket.IO로 변경 사항 실시간 반영",
      "- 세대 관리: 목록(검색/필터/페이징), 권한 부여·회수, 데이터 내보내기",
      "- 문서 출력: pdfMake·xlsx.js로 PDF/엑셀 출력 기능",
      "- 인증/권한: 역할별 접근 통제 및 메뉴 가시성 제어",
      "- 게시판/공지: 게시글 등록·수정·삭제, 댓글 관리",
    ],
    type: "company",
    members: { frontend: 2, backend: 1 },
  },
  {
    id: "chaedle",
    title: "채들",
    period: { start: "2023.08", end: "2024.03" },
    images: [{ src: "/chaedle.jpg", alt: "채들 어드민" }],
    callout:
      "하자(AS) 접수·조회, 사전점검/입주이사 예약, 처리 진행상태 확인·서명 등을 하는 입주민 앱입니다.",
    links: [],
    stacks: ["React Native", "TypeScript", "Redux", "Socket.IO", "SQLite"],
    features: [
      "- 접수 기간 타이머: 접수 가능 기간 카운트다운/만료 처리",
      "- 회원/인증: 단지·세대 권한 연동, 회원가입/로그인, 비밀번호 재설정",
      "- 예약: 생성·수정·취소, 리스트/캘린더 뷰, Socket.IO로 변경 사항 실시간 반영",
      "- 하자: 등록(사진·영상 첨부, 메모), SQLite 오프라인 저장(재전송 큐)",
      "- 알림: 이벤트 기반 푸시, 앱 내 배지 카운트 자동 갱신",
      "- 다국어: i18n 기반 한국어/영어 지원(앱 내 즉시 전환)",
    ],
    type: "company",
    members: { frontend: 3, backend: 1 },
  },
  {
    id: "zcom",
    title: "Zcom",
    images: [{ src: "/zcom.png", alt: "Zcom" }],
    callout:
      "z.com은 Next.js와 Typescript를 기반으로 X.com 클론코딩 사이트입니다.",
    links: [
      { label: "GitHub", href: "https://github.com/woals7480/zcom-next" },
    ],
    stacks: [
      "Next.js",
      "TypeScript",
      "React Query",
      "Next Auth",
      "Socket.IO",
      "MSW",
      "Zustand",
    ],
    features: [
      "- 사용자 회원가입/로그인/로그아웃 (Next Auth + Credentials)",
      "- 게시글 작성/수정/삭제",
      "- 게시글 좋아요, 댓글 기능",
      "- 무한 스크롤 및 인피니트 페이징 (React Query)",
      "- 옵티미스틱 업데이트 및 롤백 처리",
      "- 실시간 채팅 (Socket.IO + React Query)",
      "- MSW를 이용한 개발용 Mock API → 실제 API 손쉬운 전환",
      "- 상태 관리 (Zustand)",
      "- SSR로 SEO 최적화",
    ],
    type: "personal",
    members: { frontend: 1 },
  },
  {
    id: "market",
    title: "딸기마켓",
    images: [{ src: "/market.png", alt: "market" }],
    callout:
      "딸기마켓은 Next.js와 Graphql을 기반으로 한 중고물품거래사이트입니다.",
    links: [
      {
        label: "GitHub",
        href: "https://github.com/woals7480/freeboard_frontend",
      },
    ],
    stacks: [
      "Next.js",
      "TypeScript",
      "Recoil",
      "GraphQL",
      "Apollo GraphQL",
      "Emotion",
    ],
    features: [
      "- 사용자 회원가입/로그인/로그아웃",
      "- 상품 게시글 작성/수정/삭제",
      "- 상품 게시글 좋아요, 댓글 기능",
      "- 검색기능 최적화 (Lodash)",
      "- 무한스크롤(react-infinite-scroller)",
      "- 결제기능(PortOne)",
      "- 상태 관리 (Recoil)",
      "- 지도 연동(kakao map)",
      "- 웹 에디터(react-quill)",
    ],
    type: "personal",
    members: { frontend: 1 },
  },
];
