import type { Metadata } from "next";
import "./global.css.ts";
import SiteHeader from "@/app/_components/SiteHeader";
import { cookies } from "next/headers.js";
import { isTheme, Theme, THEME_COOKIE } from "@/lib/theme";
import * as s from "./layout.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const t = cookieStore.get(THEME_COOKIE)?.value;
  const theme: Theme = isTheme(t) ? t : "light"; // 기본값 'light'

  const navItems = [
    { label: "Home", href: "/", external: false },
    { label: "Resume", href: "/resume", external: false },
    { label: "Portfolio", href: "/portfolio", external: false },
    { label: "Github", href: "/github", external: true },
  ];

  return (
    <html lang="ko" data-theme={theme}>
      <head />
      <body className={s.RootBody}>
        <SiteHeader navItems={navItems} />
        <main className={s.RootMain}>{children}</main>
      </body>
    </html>
  );
}
