import type { Metadata } from "next";
import "./global.css.ts";
import SiteHeader from "@/app/_components/SiteHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cta = { label: "Contact", href: "/contact", external: true };
  const navItems = [
    { label: "Home", href: "/", external: true },
    { label: "About", href: "/about", external: true },
    { label: "Contact", href: "/contact", external: true },
  ];

  return (
    <html lang="ko">
      <head />
      <body>
        <SiteHeader cta={cta} navItems={navItems} />
        {children}
      </body>
    </html>
  );
}
