import type { ResumeData } from "@/app/resume/_types";

export const RESUME_DATA: ResumeData = {
  profile: {
    name: "정재민",
    title: "프론트엔드 개발자",
    subtitle: "접근성과 성능을 기본으로, 누구나 쓰기 쉬운 웹을 만듭니다.",
    photoUrl: "/profile.png",
  },
  contact: {
    email: "woals7480@gmail.com",
    phone: "010-8440-7480",
    github: {
      href: "https://github.com/woals7480",
      label: "github.com/woals7480",
    },
  },
  introduce: [
    "디지털시각디자인으로 웹에 입문한 뒤, 주식회사 이음에서 2년간 Vue3 관리자페이지와 React Native 입주민앱을 개발했습니다.",
    "공통 컴포넌트와 상태관리 재설계로 개발·유지보수 효율을 높였고, 실시간 예약 알림과 일정 관리 최적화, 대시보드 개선으로 예약 변경 오류를 줄이며 하자 접수 완료율과 응답 속도를 끌어올렸습니다.",
    "그 결과 페이지 로딩 속도 개선과 신규 페이지 개발 시간 단축 등 가시적 성과를 만들었습니다. 문제를 끝까지 책임지고 상황에 맞게 유연하게 해결책을 제시하는 개발자로, 최신 프론트엔드 트렌드를 빠르게 학습·적용해 더 나은 UX를 지속적으로 만들어가겠습니다",
  ],
  career: [
    {
      role: "프론트엔드 개발자",
      org: "(주) 이음",
      period: "2023.07 – 2025.06",
      bullets: [
        "Vue3 기반 관리자페이지 프론트엔드 개발 및 유지보수",
        "- 하자접수, 예약일정 관리, 문서 출력, 엑셀 다운로드 등 기능 구현",
        "React Native 기반 입주민앱 프론트엔드 개발 및 유지보수",
        "- 하자접수, 예약일정 관리, 푸시알림 등 핵심 기능 구현",
      ],
    },
  ],
  projects: [
    {
      title: "채들 관리자 페이지",
      subtitle:
        "입주민 앱에서 들어온 하자·예약 데이터를 실시간으로 확인하고 피드백/처리 현황을 관리하는 통합 관리자페이지",
      type: "company",
      meta: "2025.01 ~ 2025.05",
      bullets: [
        "- Vue3 및 Vuetify3 기반 관리자페이지 UI/UX 설계 및 구현",
        "- 재사용 가능한 공통 컴포넌트 개발 및 유지보수",
        "- Vuex를 통한 전역 상태관리 및 API 연동",
        "- 하자접수, 예약관리 기능 구현",
        "- pdfMake, xlsx.js를 활용한 문서 출력 및 엑셀 다운로드 기능 구현",
        "- Chart.js를 이용한 관리자 대시보드 주요 지표 시각화",
        "- Socket.IO 기반 실시간 예약관리 기능 구축",
      ],
      tags: [
        "Vue3",
        "TypeScript",
        "Vuex",
        "pdfMake",
        "xlsx.js",
        "Chart.js",
        "Socket.IO",
      ],
    },
    {
      title: "채들",
      subtitle:
        "하자(AS) 접수·조회, 사전점검/입주이사 예약, 처리 진행상태 확인·서명 등을 하는 입주민 앱",
      type: "company",
      meta: "2024.08 ~ 2025.03",
      bullets: [
        "- React Native 기반 입주민앱 주요 기능(하자접수, 예약 일정 관리, 푸시알림) 구현",
        "- Redux를 활용한 전역 상태관리 및 데이터 흐름 개선",
        "- SQLite 기반 오프라인 모드 지원으로 네트워크 불안정 상황에서도 주요 기능 사용 가능",
        "- Socket.IO 기반 예약 실시간 동기화 및 알림 기능 구현",
      ],
      tags: ["React Native", "TypeScript", "Redux", "SQLite", "Socket.IO"],
    },
    {
      title: "Z.com",
      subtitle: "z.com은 Next.js와 Typescript를 기반으로 X.com 클론코딩 사이트",
      type: "personal",
      bullets: [
        "- 사용자 회원가입/로그인/로그아웃 (Next Auth + Credentials)",
        "- 게시글 작성/수정/삭제",
        "- 게시글 좋아요, 댓글 기능",
        "- 무한 스크롤 및 인피니트 페이징 (React Query)",
        "- 옵티미스틱 업데이트 및 롤백 처리",
        "- 실시간 채팅 (Socket.IO + React Query)",
        "- MSW를 이용한 개발용 Mock API → 실제 API 손쉬운 전환",
        "- 상태 관리 (Zustand)",
        "- SSR로 SEO 최적화",
      ],
      tags: [
        "NextJS",
        "TypeScript",
        "React Query",
        "Next Auth",
        "Socket.IO",
        "MSW",
        "Zustand",
      ],
      link: "https://github.com/woals7480/zcom-next",
    },
    {
      title: "딸기마켓",
      subtitle:
        "딸기마켓은 Next.js와 Graphql을 기반으로 한 중고물품거래사이트입니다",
      type: "personal",
      bullets: [
        "- 사용자 회원가입/로그인/로그아웃",
        "- 상품 게시글 작성/수정/삭제",
        "- 상품 게시글 좋아요, 댓글 기능",
        "- 검색기능 최적화 (Lodash)",
        "- 무한스크롤(react-infinite-scroller)",
        "- 결제기능(PortOne)",
        "- 상태 관리 (Recoil)",
        "- 지도 연동(kakao map)",
        "- 웹 에디터(react-quill)",
      ],
      tags: [
        "NextJS",
        "TypeScript",
        "Recoil",
        "Graphql",
        "Apollo Graphql",
        "Emotion",
      ],
      link: "https://github.com/woals7480/freeboard_frontend",
    },
  ],
  skills: [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Next.js",
    "Vue3",
    "TypeScript",
    "React Query",
    "Vuex",
    "Redux",
    "Emotion",
    "Vuetify",
    "vanilla-extract",
    "Chart.js",
    "Node.js",
    "Socket.IO",
    "GraphQL",
  ],
  education: [
    {
      school: "[인프런x코드캠프] 부트캠프에서 만든 고농축 프론트엔드 코스 수료",
      major: "Next.js, TypeScript, Graphql 기반의 코스",
      period: "2023.01 ~ 2023.05",
    },
    {
      school: "노마드코더 코코아클론 코스 수료",
      major: "HTML, CSS 기반의 코스",
      period: "2021.11 ~ 2021.11",
    },
    {
      school: "디지털시각디자인 수료",
      major: "포토샵, 일러스트, HTML, CSS 기반의 웹디자인 국비교육",
      period: "2021.01 ~ 2021.07",
    },
  ],
  certification: [
    {
      name: "컴퓨터그래픽스운용기능사",
      issuer: "한국산업인력공단",
      issueDate: "2021.06",
    },
    {
      name: "그래픽기술자격(GTQ) 1급",
      issuer: "한국생산성본부(KPC)",
      issueDate: "2020.12",
    },
    {
      name: "컴퓨터활용능력1급",
      issuer: "대한상공회의소",
      issueDate: "2020.06",
    },
  ],
};
